version: '3.8'

services:
  postgres:
    image: postgres:15.6
    environment:
      POSTGRES_DB: nanalyzer
      POSTGRES_USER: nanalyzer
      POSTGRES_PASSWORD: nanalyzer
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "nanalyzer"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./models:/app/models
      - ./data:/app/data
    environment:
      - APP_ENV=development
      - DEBUG=true
      - DATABASE_URL=postgresql+asyncpg://nanalyzer:nanalyzer@postgres:5432/nanalyzer
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - REACT_APP_WS_URL=ws://localhost:8000
    depends_on:
      backend:
        condition: service_started

volumes:
  models:
  data:
  postgres-data:
